### ISSUE TITLE
Cannot load plugin

### ISSUE THREAD

**Issue by maning** [iandees/josm-fieldpapers#1]
Using the the latest JOSM r6070.

I get this error after restarting JOSM.

Could not load plugin fieldpapers because the plugin main class 'org.openstreetmap.josm.plugins.fieldpapers.FieldPapersPlugin' was not found. Delete from preferences?

**Comment by iandees** [comment]
Hmm, I'm confused about why that's happening. It was working fine before I uploaded the file to github but now it isn't. I'll try uploading it again...

**Comment by iandees** [comment]
JOSM doesn't follow redirects when downloading plugins, so installing the plugin from the Preferences pane won't work. Go [here](https://github.com/iandees/josm-fieldpapers/releases/tag/0.1) and download the .jar file. Put it in your `~/.josm/plugins` dir and then check the Preferences pane to enable the plugin.

**Comment by maning** [comment]
Yes, found out about it just now.  Downloading directly and copying to `~/.josm/plugins` work.
The plugin is now activated but when I added a sample snapshot, I only get white background.
The sample snapshot is here: http://fieldpapers.org/snapshot.php?id=lw4895cx#17/14.60305/120.98095

**Comment by iandees** [comment]
Try [this new release](https://github.com/iandees/josm-fieldpapers/releases/tag/0.2). It works a bit better and loads your example (at least for me).

**Comment by maning** [comment]
Works!
![screen shot 2013-07-18 at 9 16 54 am](https://f.cloud.github.com/assets/353700/816500/c31ba632-ef47-11e2-92f3-23808450e823.png)
